language: node_js
node_js:
  - 16

services:
  - docker

before_install:
  - echo "nothing needs to be installed"

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy yalecthub/reverseproxy:v2
  - docker tag udagram-api-user yalecthub/udagram-api-user:v2
  - docker tag udagram-api-feed yalecthub/udagram-api-feed:v2
  - docker tag udagram-frontend yalecthub/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yalecthub/reverseproxy:v2
  - docker push yalecthub/udagram-api-user:v2
  - docker push yalecthub/udagram-api-feed:v2
  - docker push yalecthub/udagram-frontend:v2