apiVersion: v1
data:
  aws_access_key_id: QUtJQVNMWktFQ1pOQk8yRDdHUDMK
  aws_secret_access_key: QUU0WE45S01PUmVPdUdHdnRCRFBNZGl5M0JQdXhSclZaRUIrM1M5Swo=
kind: Secret
metadata:
  creationTimestamp: null
  name: aws
type: string