apiVersion: v1
data:
  aws_access_key_id: QUtJQVdGWkozV05FWDNPT1JXV1IK
  aws_secret_access_key: dEMzV1F4QmtzSWxjTy9LTHpZcFpWbWtGaE1vbjlQVmFVbmwyc2VISAo=
kind: Secret
metadata:
  creationTimestamp: null
  name: aws
type: string