apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user
  name: backend-user
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-user
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-feed
  name: backend-feed
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-feed
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
  selfLink: /api/v1/namespaces/default/services/frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
  namespace: default
  selfLink: /api/v1/namespaces/default/services/reverseproxy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reverseproxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}