language: node_js
node_js:
  - 16

services:
  - docker

before_install:
  - echo "nothing needs to be installed"

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy azconcept-droid/reverseproxy:v1
  - docker tag udagram-api-user azconcept-droid/udagram-api-user:v1
  - docker tag udagram-api-feed azconcept-droid/udagram-api-feed:v1
  - docker tag udagram-frontend azconcept-droid/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push azconcept-droid/reverseproxy:v1
  - docker push azconcept-droid/udagram-api-user:v1
  - docker push azconcept-droid/udagram-api-feed:v1
  - docker push azconcept-droid/udagram-frontend:v1